spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.netroundhouse.proxy.rlwy.net:55001/railway
    username: root
    password: rFFjKorxSPGQyFxjensdKnkNBPSozVnD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8081
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    enabled=true
